name: Debug
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: nsdavidson/github-action-explore-debug@master
        with:
          jq_selector: ".pull_request"
          example: ${{ secrets.EXAMPLE }}