name: Debug
on:
  push:
    branches:
      - main
jobs:
  output-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p output
      - run: echo hello > output/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: artifact-out
          path: output/world.txt
